version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
  c2:
    image: iqtlabs/edgetech-c2:latest
    build:
      context: ./c2
      dockerfile: ./Dockerfile
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt
    env_file:
      - .env
