version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    build:
      context: ./mqtt
      dockerfile: ./Dockerfile
    restart: unless-stopped
  c2c:
    image: iqtlabs/edgetech-c2c:latest
    network_mode: "host"
    build:
      context: ../edgetech-c2c/c2c
      dockerfile: ./Dockerfile
    environment:
      - NEXT_FILE_TOPIC=/AISonobuoy/<HOSTNAME>/C2C/edgetech-c2c/string
      - MQTT_IP=mqtt
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    restart: unless-stopped
    depends_on: 
      - mqtt
